meta_product_name: "OurHood"
meta_title: "OurHood - Gift Boxes and Unique Products"
meta_description: "Gift boxes and thousands of unique products from Istanbul's most authentic stores."
meta_image: "gift_boxes.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
